### ISSUE TITLE
Photo Kind not Displaying Information from Response Properties Box

### ISSUE THREAD

**Issue by mrkrndvs** [dshanske/indieweb-post-kinds#184]
I am adding in information associated with author and source, however this is not being displayed when published.

(Originally published at: https://collect.readwriterespond.com/photo-kind-not-displaying-information-from-response-properties-box/)

**Comment by dshanske** [comment]
Which information?

**Comment by mrkrndvs** [comment]
Everything but the name of the image.

Here is the editor:

![screenshot_20180626-071706](https://user-images.githubusercontent.com/13294754/41876523-69778494-7911-11e8-80bb-102f5ed00d3a.png)

While here is the published post:

![screenshot_20180626-071724](https://user-images.githubusercontent.com/13294754/41876534-724c84de-7911-11e8-9113-637b9a525432.png)

**Comment by chrisaldrich** [comment]
Replied to [Photo Kind not Displaying Information from Response Properties Box · Issue #184 · dshanske/indieweb-post-kinds](https://github.com/dshanske/indieweb-post-kinds/issues/184) _( GitHub)_

&gt; I am adding in information associated with author and source, however this is not being displayed when published.

[@mrkrndvs](https://collect.readwriterespond.com/photo-kind-not-displaying-information-from-response-properties-box/) This is because the photo template doesn’t call these particular details even though they may be provided. I could see an occasional use for including them, particularly to give credit to a photo that was taken by someone else, while in practice most may not use this because they’re posting their own photos.

In the meanwhile, it may not be too tough to cut/paste bits of appropriate [code from other templates](https://github.com/dshanske/indieweb-post-kinds/tree/master/views) to get these to display the way you want them when they exist. You can create a custom photo template named `kind-photo.php` and put it in a folder entitled `kind_views` in either your theme or (preferably) in your child theme so it isn’t overwritten on plugin update.

I do still wish there were a master template in the set (heavily commented and unused) that used every variation of data that could be displayed (or perhaps even calculated for display) so that non-programmers could attempt to more easily cut/paste templates to get them to do what they wanted.

(Originally published at: https://boffosocko.com/2018/07/15/reply-to-photo-kind-not-displaying-information-from-response-properties-box/)

**Comment by dshanske** [comment]
As this will be invalidated in the new version, as the photo metadata will be pulled out of the attachment itself, instead of the citation, closing this in favor of a new issue.

There is a new function I'll be building to replace the use of the built-in gallery that can show this data.
