### ISSUE TITLE
Consider separating parsing library to support feed parsing for a reader

### ISSUE THREAD

**Issue by dshanske** [dshanske/indieweb-post-kinds#188]
Thinking of making this available to parse for a Microsub reader

**Comment by jackjamieson-indieauth** [comment]
Obviously, I'm in favour of this!  

I've been playing around with the Parse_MF2 class and finding it very useful for https://github.com/jackjamieson2/yarns-microsub-server

One change I made was to set `parse_entry` to a public function.  This allows me to quickly parse individual posts in a feed without having to use `mf2parse` on individual post permalinks.  I'm finding this necessary to display feed previews in a timely fashion (see https://indieweb.org/Microsub-spec#Preview)

**Comment by jackjamieson2** [comment]
Obviously, I'm in favour of this!

I've been playing around with the `Parse_MF2` class and finding it very useful for https://github.com/jackjamieson2/yarns-microsub-server

One change I made was to set `parse_entry` to a public function. This allows me to quickly parse individual posts in a feed without having to use `mf2parse` on individual post permalinks. I'm finding this valuable to display feed previews in a timely fashion (see https://indieweb.org/Microsub-spec#Preview)

**Comment by jackjamieson2** [comment]
hi @dshanske,

I thought I'd mark up the changes I've made to class-parse-mf2.php in Yarns, since they might be useful to note.

I've marked up each change with comments.  Each comment is searchable with "Note to GWG:"

https://github.com/jackjamieson2/yarns-microsub-server/blob/Parse_MF2-discussion/includes/class-parse-mf2.php

I think it might be a good idea to include/adapt those changes in a parser library, or at least they might be useful to consider.

With those changes, parsing is working quite well right now, with a few exceptions.

**1.  H-Events**  
- https://aaronparecki.com/2018/08/17/1/
  - Does not parse start and end time (because they are stored in "start" and "end" instead of "published "or "updated")
  - Does not capture photo (not sure why)


**2. Checkins **
- This might be better resolved client side, however.
- https://david.shanske.com/2018/08/09/2042/ does not display correctly in Together, but looks fine in Monocle
- The best case would be if Together displayed the checkin as Monocle does
Otherwise, it could be worth copying checkin[properties][name] to the post name if there is no name, summary, or content.


Other than that, parsing seems to be pretty solid.  I should set up some more systematic tests, but this will take a bit of research to learn how to do it. 


Yarns issues for reference: 
- H-events https://github.com/jackjamieson2/yarns-microsub-server/issues/9
- Checkins https://github.com/jackjamieson2/yarns-microsub-server/issues/13

**Comment by dshanske** [comment]
Some of the parsing code to clean the formats came from https://github.com/barnabywalters/php-mf-cleaner , but that is over 5 years old and isn't maintained anymore, and a lot of improvements went into php-mf2 since then, so some checks aren't needed anymore.

**Comment by dshanske** [comment]
I'm working on some structural improvements and simplifications now.

**Comment by jackjamieson2** [comment]
Excellent! Please let me know if there is anything I can help test etc.

**Comment by dshanske** [comment]
Follow my parse Branch for now

**Comment by dshanske** [comment]
I am probably going to refactor the mf2 and the non mf2 pieces to be more cohesive.

**Comment by dshanske** [comment]
Also going to have the functionality return jf2

**Comment by jackjamieson2** [comment]
Testing out the updates now.  Overall very smooth!

A few observations
1) Entry author is returned as mf2 instead of jf2. I resolved this by calling mf2_to_jf2 in my parser:

`$the_item['author'] = mf2_to_jf2($the_item['author']);`

2) 'in-reply-to' is stored as an array of name, url, and type, which seems to cause Together to crash.  I was able to fix this by stripping everything but the url (`$data['in-reply-to'] = $data['in-reply-to']['url'];`).  

   - Together's console reports the following error: https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bname%2C%20url%2C%20type%7D&args[]=
   -I'm not sure if there are other properties that could cause the same error -> I'll do some more tesitng


3) Some sites (e.g. david.shanske.com) are parsed with multiple author photos. This also causes Together to crash.  Doesn't make sense to have multiple photos anyway. I removed the additional photos on my end, and I'm not sure whether it makes sense to keep it that way or whether that should be done in parse-this

I need to test with a larger variety of feeds, but that's my initial report.  Apart from the issues noted here, it seems very good

**Comment by dshanske** [comment]
@jackjamieson2 Can you refile any issues over in the new parse this repo? I will be working this issue there

**Comment by jackjamieson2** [comment]
@dshanske: Will do - just trying to get the latest version working (installed via composer) and then I'll test my previous issues and confirm if they still stand.  From here I'll make sure all my parsing issues are filed in the parse-this repo
