### ISSUE TITLE
"Summary" field not maintaining data

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/indieweb-post-kinds#30]
The field "Summary" under the "Citation" tab in prior versions was constantly self-updating with details of the original website/URL and not allowing the editor to make permanent changes which then propagate to their site.  

Under the changes in v2.2.0 it seems like one can finally make changes to this field manually, but after saving/publishing, the field seems to self-delete and any future updates to the post result in the "Summary" text disappearing from the final post (at least from my tests with bookmark post types.)

**Comment by dshanske** [comment]
This is a problem I'm still working on, but not for the reason you might think. 

The parsing code I wrote and continue to iterate on to get the data gets both content and summary when marked up. The issue was which to use. 

I was thinking if it is a repost that the content should be the post content, not the citation summary.

**Comment by dshanske** [comment]
This conflicts though with one known usage

**Comment by dshanske** [comment]
Try the version I just pushed to wordpress.org. It has a summary fix and a few other changes, but I still have to figure out what to do bigger picture. 

I rewrote the entire saving function.
