### ISSUE TITLE
Photos Removed From Posts After Editing Tags/Post Kinds

### ISSUE THREAD

**Issue by kevinjtracy** [dshanske/indieweb-post-kinds#324]
I'm using Indigenous on Android to add posts to my website.  By creating a "note" in the app and uploading one or more photos to it, I am able to create a "Photo" post kind.  A little confusing, but it works.

Unfortunately, after the post has been created, I've noticed that editing the tags (at least in WordPress) causes the photo to disappear from the post.

I suspect this happens whenever any edit is made.  I previously tried changing the Post Kind of one of these from "photo" to "eat" and the same thing happened (photo dropped from the post).  I assumed the "eat" post kind didn't support photos, but I'm thinking this bug is to blame now.

**Comment by dshanske** [comment]
This is interesting... I'll test this. I did a lot of work on photo posts and photos in other posts because that's what I'm working on on my own website.

**Comment by stephenpieper** [comment]
I've just updated and I've also noticed that photos are not being shown in checkin posts. These are photos that have come with OwnYourSwarm posts.

**Comment by dshanske** [comment]
I will check that as well. I use own your swarm, but I always add the photo later

**Comment by dshanske** [comment]
From Micropub, Post Kinds using Post Type Discovery. So if Indigenous sends a note with a photo property, that is a photo post. 

I just tested the adding of a tag and could not reproduce it hiding the photo when editing tags. If you do change from a photo posts to a different type, it will no longer show the photo by default. There is a reason for this, involving me trying to remove the photo displaying twice if someone put it into the content.

So, in order for me to figure out how to address this, let me bounce the issue off you. There are three places photos can be identified. In the content itself, in the photo property sent by Micropub and stored in the post metadata, and by looking at what photos are attached to the post.

For all properties, it will display photos added to the content. If it finds any photos in the content, it will stop to avoid duplication. It assumes you inserting one means you want to override the auto-insert. 

Right now, only when you have a photo post can you edit the photo property(it appears where the URL for the checkin or other property appears). Otherwise it isn't accessible. 

So, clearly this is a mistake for various use cases. Options...

* Always autodisplay any photo property sent for any type of post. Figure out a way to show editing options for photos 
* Automatically any photo attached to the post(excerpt for in an article which would require an explicit request), and only look in the photo property if nothing is attached to the post.

I'm leaning toward the second one, as it is more WordPress than Micropub, and maps nicely as the Micropub plugin sideloads all images sent via Micropub.

**Comment by dshanske** [comment]
@stephenpieper Specifically for checkin posts, I found the error.

**Comment by kevinjtracy** [comment]
> _> I just tested the adding of a tag and could not reproduce it hiding the photo when editing tags._


That's really weird.  I don't have any plugins that should be affecting that.  I'll have to investigate this closer on my end to figure out what's happening.  In the meantime, I'll just be careful to identify the tags before I submit it and militant about not changing them if I mess up.

_> If you do change from a photo posts to a different type, it will no longer show the photo by default. There is a reason for this, involving me trying to remove the photo displaying twice if someone put it into the content.
> 
> So, in order for me to figure out how to address this, let me bounce the issue off you. There are three places photos can be identified. In the content itself, in the photo property sent by Micropub and stored in the post metadata, and by looking at what photos are attached to the post.
> 
> For all properties, it will display photos added to the content. If it finds any photos in the content, it will stop to avoid duplication. It assumes you inserting one means you want to override the auto-insert.
> 
> Right now, only when you have a photo post can you edit the photo property(it appears where the URL for the checkin or other property appears). Otherwise it isn't accessible.
> 
> So, clearly this is a mistake for various use cases. Options...
> 
> * Always autodisplay any photo property sent for any type of post. Figure out a way to show editing options for photos
> * Automatically any photo attached to the post(excerpt for in an article which would require an explicit request), and only look in the photo property if nothing is attached to the post.
> 
> I'm leaning toward the second one, as it is more WordPress than Micropub, and maps nicely as the Micropub plugin sideloads all images sent via Micropub._

To be honest, I'm still REALLY new at IndieWeb and trying to figure out how to make this work best for me.  I'm not the best person to bounce UI issues off of (at least not yet). Either way, it sounds like you'd be solving my problem of wanting to change a post kind from one thing to another (specifically photo to eat or drink), so I don't have an opinion here. Unless someone else sees this issue and has a strong opinion on it one way or the other, I say, "Trust your gut." :)

I do appreciate you taking the time to look into this.

**Comment by dshanske** [comment]
Did the update I released last night resolve your issue?

**Comment by stephenpieper** [comment]
That fixed my checkin issue but I'm getting double photos in photo posts now. Alt text is appearing at the top of photo posts too.

**Comment by dshanske** [comment]
@stephenpieper Fixed this yesterday. Will be fixing a few other things and releasing another point update.
