### ISSUE TITLE
Use $kind instead of $type in templates.

### ISSUE THREAD

**Issue by miklb** [dshanske/indieweb-post-kinds#77]
In the `kind.php` template the [section class](https://github.com/dshanske/indieweb-post-kinds/blob/master/includes/views/kind.php#L61) uses `<?php echo $type; ?>`.

I believe that should now be `<?php echo $kind; ?>` 

But I might be missing something, thus I didn't open a pull request for a minor change. I'd be glad to send one if it would help.

Cheers, and thanks for all the improvements. Very exciting!

**Comment by dshanske** [comment]
The variables are set at the top instead of outside. I can change to be more descriptive, but you can use $kind in your templates. $type in the template is being used for the mf2 properties. In a specific, not general template, you shouldn't bother and instead just put in the mf2 property and kind anyway.

**Comment by miklb** [comment]
I don't follow, where is $type defined?

**Comment by dshanske** [comment]
It doesn't need to be anymore.

**Comment by miklb** [comment]
Totally overlooked the case switch. Forest. Trees.
